name: ranch_conservation_predictor
description: A simple Flutter UI for the Ranch Conservation Predictor API.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.1.1
  share_plus: ^6.3.0
  # fl_chart removed due to Flutter SDK compatibility issues; using custom painter instead

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
